const team = [
  {
    name: "Dr. N.Venkateswaran",
    position: "Chairman",
    desc: "Professor, Dept. of ECE, Sri SivaSubramaniya Nadar College Of Engineering",
    email: "venkateswaran.iete@gmail.com",
    img: "/team/venkateswaran.jpg",
  },
  {
    name: "Dr. Tata Sudhakar",
    position: "Immd Post Chairman",
    desc: "",
    email: "tatasudhakar@gmail.com",
    img: "/team/tata_sudhakar.jpeg",
  },
  {
    name: "Mr. Shakthi Murugan",
    position: "Honarary Secretary",
    desc: "Assistant Professor, Dept. of ECE, Jeppiaar Maamallan Engineering College",
    email: "shakthimuruganece@gmail.com",
    img: "/noprofile.png",
  },
  {
    name: "Mrs. T J Jeyaprabha",
    position: "Honarary Treasurer",
    desc: "Assistant Professor, Dept. of ECE, Sri Venkateswara College of Engineering",
    email: "jprabha@svce.ac.in",
    img: "/team/jeyaprabha.jpg",
  },
  {
    name: "Dr. C Udayakumar",
    position: "EC Member",
    desc: "",
    email: "cukumar@gmail.com",
    img: "/noprofile.png",
  },
  {
    name: "Dr. V Thulasibai",
    position: "EC Member",
    desc: "",
    email: "thulasi9840@gmail.com",
    img: "/noprofile.png",
  },
  {
    name: "Mr. D Vijendrababu",
    position: "EC Member",
    desc: "",
    email: "dvijendrababu@gmail.com",
    img: "/team/vijendrababu.jpg",
  },
  {
    name: "Shri Ganapathy Suresh",
    position: "EC Member",
    desc: "",
    email: "lovechennai@yahoo.com",
    img: "/noprofile.png",
  },
  {
    name: "Shri S Arun Kumar",
    position: "EC Member",
    desc: "",
    email: "arunsundar.s@cvrde.drdo.in",
    img: "/team/arunkumar.jpeg",
  },
  {
    name: "Shri S Madivaanan",
    position: "EC Member",
    desc: "",
    email: "madivaanan.s@gmail.com",
    img: "/noprofile.png",
  },
  {
    name: "Dr. Vaishali D",
    position: "Co-opted Member",
    desc: "",
    email: "vaishali.b@vdp.srmuniv.ac.in",
    img: "/team/vaishali.jpg",
  },
  {
    name: "Mr. Arun",
    position: "Co-opted Member",
    desc: "",
    email: "snatarajan1967@gmail.com",
    img: "/team/arun.jpeg",
  },
  {
    name: "Dr. K. Sumathi",
    position: "Co-opted Member",
    desc: "",
    email: "sumathi.ece@sairam.edu.in",
    img: "/team/sumathi.jpeg",
  },
];

export default team;
